import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { useCartStore } from '../../stores/cartStore';
import { X, Trash2, Plus, Minus, ArrowRight, ShoppingBag } from 'lucide-react';
import { Button } from '../ui/Button';
export const CartDrawer = () => {
    const { items, isOpen, setIsOpen, removeItem, updateQuantity, getSubtotal } = useCartStore();
    const navigate = useNavigate();
    const subtotal = getSubtotal();
    if (!isOpen)
        return null;
    const handleCheckout = () => {
        setIsOpen(false);
        navigate('/checkout');
    };
    return (_jsxs("div", { className: "fixed inset-0 z-50 overflow-hidden", role: "dialog", "aria-modal": "true", children: [_jsx("div", { className: "fixed inset-0 bg-[#071521]/50 backdrop-blur-xs transition-opacity", onClick: () => setIsOpen(false) }), _jsx("div", { className: "fixed inset-y-0 right-0 max-w-full flex pl-10", children: _jsxs("div", { className: "w-screen max-w-md bg-white border-l border-[#E2E8F0] shadow-2xl flex flex-col", children: [_jsxs("div", { className: "p-4 sm:p-5 border-b border-[#E2E8F0] flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(ShoppingBag, { className: "h-5 w-5 text-[#0B1F33]" }), _jsxs("h2", { className: "text-base font-bold text-[#111827] font-heading", children: ["Your Hardware Cart (", items.reduce((s, i) => s + i.quantity, 0), ")"] })] }), _jsx("button", { onClick: () => setIsOpen(false), className: "p-1 rounded-[6px] text-[#64748B] hover:text-[#111827] hover:bg-[#F1F5F9]", "aria-label": "Close cart", children: _jsx(X, { className: "h-5 w-5" }) })] }), _jsx("div", { className: "flex-1 overflow-y-auto p-4 sm:p-5 divide-y divide-[#E2E8F0]/80", children: items.length === 0 ? (_jsxs("div", { className: "h-full flex flex-col items-center justify-center text-center p-6", children: [_jsx("div", { className: "h-16 w-16 rounded-full bg-[#F3F4F6] flex items-center justify-center text-[#94A3B8] mb-4", children: _jsx(ShoppingBag, { className: "h-8 w-8" }) }), _jsx("h3", { className: "text-sm font-bold text-[#111827]", children: "Your cart is empty" }), _jsx("p", { className: "mt-1 text-xs text-[#64748B] max-w-xs", children: "Explore our pure sine wave inverters, online UPS systems, and solar charge controllers." }), _jsx("div", { className: "mt-5", children: _jsx(Button, { variant: "primary", size: "sm", onClick: () => {
                                                setIsOpen(false);
                                                navigate('/shop');
                                            }, children: "Browse Hardware Store" }) })] })) : (items.map((item) => (_jsxs("div", { className: "py-4 flex gap-4", children: [_jsx("img", { src: item.product.images[0], alt: item.product.name, className: "h-18 w-18 object-cover rounded-[8px] border border-[#E2E8F0] shrink-0" }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h4", { className: "text-xs font-semibold text-[#111827] line-clamp-2", children: item.product.name }), _jsxs("p", { className: "text-[11px] font-mono text-[#64748B] mt-0.5", children: ["SKU: ", item.product.sku] }), _jsxs("div", { className: "mt-1 font-semibold text-xs text-[#0B1F33]", children: ["\u20A6", item.product.price.toLocaleString()] }), _jsxs("div", { className: "mt-2.5 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center border border-[#E2E8F0] rounded-[6px] bg-white", children: [_jsx("button", { onClick: () => updateQuantity(item.product.id, item.quantity - 1), className: "p-1 hover:bg-[#F1F5F9] text-[#64748B] transition-colors rounded-l-[5px]", "aria-label": "Decrease quantity", children: _jsx(Minus, { className: "h-3 w-3" }) }), _jsx("span", { className: "px-2 text-xs font-semibold text-[#111827]", children: item.quantity }), _jsx("button", { onClick: () => updateQuantity(item.product.id, item.quantity + 1), className: "p-1 hover:bg-[#F1F5F9] text-[#64748B] transition-colors rounded-r-[5px]", "aria-label": "Increase quantity", children: _jsx(Plus, { className: "h-3 w-3" }) })] }), _jsx("button", { onClick: () => removeItem(item.product.id), className: "text-[#94A3B8] hover:text-[#DC2626] transition-colors p-1", "aria-label": "Remove item", children: _jsx(Trash2, { className: "h-4 w-4" }) })] })] })] }, item.product.id)))) }), items.length > 0 && (_jsxs("div", { className: "p-4 sm:p-5 border-t border-[#E2E8F0] bg-[#F8FAFC] space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between text-xs text-[#64748B]", children: [_jsx("span", { children: "Estimated Subtotal" }), _jsxs("span", { className: "font-bold text-sm text-[#111827]", children: ["\u20A6", subtotal.toLocaleString()] })] }), _jsx("p", { className: "text-[11px] text-[#64748B]", children: "Taxes, freight calculation, and official invoice generated at checkout." }), _jsxs("div", { className: "grid grid-cols-2 gap-2 pt-1", children: [_jsx(Button, { variant: "outline", size: "md", onClick: () => {
                                                setIsOpen(false);
                                                navigate('/cart');
                                            }, children: "View Full Cart" }), _jsx(Button, { variant: "primary", size: "md", onClick: handleCheckout, rightIcon: _jsx(ArrowRight, { className: "h-4 w-4" }), children: "Checkout" })] })] }))] }) })] }));
};
