import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Button } from '../../components/ui/Button';
import { ArrowRight, Mail, Phone } from 'lucide-react';
export const FinalCTASection = () => {
    return (_jsxs("section", { className: "bg-[#0B1F33] text-white py-20 lg:py-28 relative overflow-hidden text-center", children: [_jsx("div", { className: "absolute inset-0 opacity-[0.03] pointer-events-none", style: {
                    backgroundImage: `radial-gradient(#16C7D9 1px, transparent 1px)`,
                    backgroundSize: '24px 24px',
                } }), _jsxs("div", { className: "max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10", children: [_jsx("p", { className: "text-xs font-mono font-bold tracking-widest text-[#16C7D9] uppercase", children: "READY TO OPERATE AT ENTERPRISE SCALE?" }), _jsx("h2", { className: "text-3xl sm:text-5xl font-extrabold font-heading mt-3 tracking-tight", children: "Let's build what your business needs." }), _jsx("p", { className: "mt-4 text-base sm:text-lg text-[#94A3B8] max-w-2xl mx-auto leading-relaxed", children: "Whether you need an integrated commercial platform, specialized healthcare software, or a nationwide telematics network, Centrifuge delivers systems you can depend on." }), _jsxs("div", { className: "mt-8 flex flex-wrap items-center justify-center gap-4", children: [_jsx(Link, { to: "/contact", children: _jsx(Button, { variant: "primary", size: "lg", rightIcon: _jsx(ArrowRight, { className: "h-4 w-4" }), children: "Talk to Centrifuge" }) }), _jsx(Link, { to: "/projects", children: _jsx(Button, { variant: "outline", size: "lg", className: "bg-transparent text-white border-[#334155] hover:bg-white/10", children: "Explore Portfolio" }) })] }), _jsxs("div", { className: "mt-10 pt-8 border-t border-[#172333] flex flex-wrap items-center justify-center gap-8 text-xs text-[#94A3B8]", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Mail, { className: "h-4 w-4 text-[#16C7D9]" }), _jsx("span", { children: "info@centrifugegroup.co" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Phone, { className: "h-4 w-4 text-[#16C7D9]" }), _jsx("span", { children: "+234 (0) 803 000 1234" })] })] })] })] }));
};
