import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Terminal } from 'lucide-react';
export const TechnologySection = () => {
    const stack = [
        { category: 'Frontend & Mobile', tools: 'React, TypeScript, Tailwind CSS, React Native, Vite' },
        { category: 'Backend & APIs', tools: 'Node.js, Go, Python, GraphQL, REST, WebSockets' },
        { category: 'Databases & Spatial', tools: 'PostgreSQL, PostGIS, Redis, TimeSeries DB, SQLite' },
        { category: 'Health & Standards', tools: 'DHIS2, FHIR / HL7, OpenMRS, OpenHIE Registry Standards' },
        { category: 'Infrastructure & Edge', tools: 'Docker, Kubernetes, AWS, Cloudflare, Linux ARM' },
        { category: 'IoT & Telematics', tools: 'MQTT, Modbus RS485, CAN-Bus OBD-II, GPS GNSS' },
    ];
    return (_jsx("section", { className: "py-20 lg:py-28 bg-white border-b border-[#E2E8F0]", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-12 items-center text-left", children: [_jsxs("div", { className: "lg:col-span-5 space-y-5", children: [_jsxs("div", { className: "inline-flex items-center gap-2 px-3 py-1 rounded-[6px] bg-[#0B1F33]/5 text-xs font-mono font-semibold text-[#0B1F33]", children: [_jsx(Terminal, { className: "h-3.5 w-3.5 text-[#16C7D9]" }), _jsx("span", { children: "SYSTEM ARCHITECTURE" })] }), _jsx("h2", { className: "text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#0B1F33] font-heading tracking-tight leading-[1.15]", children: "Built for complexity." }), _jsx("p", { className: "text-base text-[#64748B] leading-relaxed", children: "We choose battle-tested, open, and scalable foundations. Our architectures are engineered to run reliably under unpredictable network conditions, high concurrent user loads, and strict data protection regulations." }), _jsxs("div", { className: "p-4 rounded-[10px] bg-[#F8FAFC] border border-[#E2E8F0] space-y-2 font-mono text-xs", children: [_jsx("div", { className: "text-[#64748B]", children: "// Centrifuge Reliability Principle:" }), _jsxs("div", { className: "text-[#111827]", children: [_jsx("span", { className: "text-[#0E7490]", children: "type" }), " ", _jsx("span", { className: "text-[#0B1F33] font-bold", children: "SystemSLA" }), " = {"] }), _jsxs("div", { className: "pl-4 text-[#475569]", children: ["offlineFirst: ", _jsx("span", { className: "text-[#16A34A]", children: "true" }), ";"] }), _jsxs("div", { className: "pl-4 text-[#475569]", children: ["dataEncryption: ", _jsx("span", { className: "text-[#B45309]", children: "'AES-256-GCM'" }), ";"] }), _jsxs("div", { className: "pl-4 text-[#475569]", children: ["auditTrailImmutable: ", _jsx("span", { className: "text-[#16A34A]", children: "true" }), ";"] }), _jsx("div", { className: "text-[#111827]", children: "}" })] })] }), _jsx("div", { className: "lg:col-span-7", children: _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4", children: stack.map((item, index) => (_jsxs("div", { className: "p-5 rounded-[12px] bg-[#F8FAFC] border border-[#E2E8F0] hover:border-[#CBD5E1] transition-colors text-left", children: [_jsx("span", { className: "text-[11px] font-bold uppercase tracking-wider text-[#64748B] block", children: item.category }), _jsx("p", { className: "text-xs font-mono font-medium text-[#111827] mt-2 leading-relaxed", children: item.tools })] }, index))) }) })] }) }) }));
};
